In [8]:
import torch

In [9]:
tensor1 = torch.randint(0, 10, (7, 7))
tensor1

tensor([[0, 2, 7, 6, 1, 1, 6],
        [3, 7, 9, 6, 4, 6, 9],
        [9, 6, 9, 3, 5, 6, 9],
        [6, 5, 7, 6, 4, 5, 4],
        [3, 8, 4, 0, 7, 9, 6],
        [8, 3, 4, 9, 1, 7, 8],
        [2, 2, 4, 5, 7, 0, 5]])

In [10]:
tensor2 = torch.randint(0, 10, (1, 7))
tensor2

tensor([[6, 1, 0, 3, 6, 6, 0]])

In [11]:
tensor2_reshaped = tensor2.transpose(0, 1)
tensor2_reshaped

tensor([[6],
        [1],
        [0],
        [3],
        [6],
        [6],
        [0]])

In [12]:
result = torch.matmul(tensor1, tensor2_reshaped)
result

tensor([[ 32],
        [103],
        [135],
        [113],
        [122],
        [126],
        [ 71]])