In [1]:
import torch

In [3]:
tensor = torch.arange(9)
tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
reshaped_tensor = torch.reshape(tensor, (3, 3))
reshaped_tensor

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [5]:
view_tensor = tensor.view(3, 3)
view_tensor

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [6]:
tensor_1 = torch.tensor([1, 2])
tensor_2 = torch.tensor([3, 4])
stacked_tensor = torch.stack([tensor_1, tensor_2], dim=0)
stacked_tensor

tensor([[1, 2],
        [3, 4]])

In [7]:
new_tensor = torch.zeros(1, 2, 3)
new_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [8]:
squeeze_tensor = torch.squeeze(new_tensor, dim=0)
squeeze_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
unsqueeze_tensor = torch.unsqueeze(tensor_1, dim=0)
unsqueeze_tensor

tensor([[1, 2]])