In [1]:
import torch
import numpy as np

In [2]:
np_array = np.array([1, 2, 3, 4, 5])
np_array

array([1, 2, 3, 4, 5])

In [3]:
np_to_tensor = torch.from_numpy(np_array)
np_to_tensor

tensor([1, 2, 3, 4, 5])

In [4]:
tensor = torch.arange(5)
tensor

tensor([0, 1, 2, 3, 4])

In [5]:
tensor_to_np = tensor.numpy()
type(tensor_to_np)

numpy.ndarray

In [6]:
tensor_to_np

array([0, 1, 2, 3, 4])