In [1]:
import torch

In [2]:
tensor1 = torch.rand(2, 3)
tensor1

tensor([[0.7062, 0.4515, 0.6233],
        [0.2821, 0.3526, 0.3271]])

In [3]:
tensor2 = torch.rand(2, 3)
tensor2

tensor([[0.6894, 0.8308, 0.8808],
        [0.5218, 0.9542, 0.8179]])

In [4]:
tensor2_reshaped = tensor2.transpose(0, 1)
tensor2_reshaped

tensor([[0.6894, 0.5218],
        [0.8308, 0.9542],
        [0.8808, 0.8179]])

In [5]:
result = torch.matmul(tensor1, tensor2_reshaped)
result

tensor([[1.4110, 1.3092],
        [0.7755, 0.7512]])