In [1]:
import torch

In [3]:
tensor1 = torch.rand(2, 3)
tensor1

tensor([[0.4226, 0.4431, 0.3998],
        [0.8163, 0.6168, 0.7127]])

In [4]:
tensor2 = torch.rand(2, 3)
tensor2

tensor([[0.6263, 0.9350, 0.4608],
        [0.3051, 0.8381, 0.2364]])

In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

/home/student/Repeat/env/lib/python3.12/site-packages/torch/cuda/__init__.py:129: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0


'cpu'

In [6]:
tensor1_gpu = tensor1.to(device)
tensor1_gpu

tensor([[0.4226, 0.4431, 0.3998],
        [0.8163, 0.6168, 0.7127]])

In [7]:
tensor2_gpu = tensor2.to(device)
tensor2_gpu

tensor([[0.6263, 0.9350, 0.4608],
        [0.3051, 0.8381, 0.2364]])